# Generated by Django 4.2.6 on 2024-02-14 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('nom_Area', models.CharField(max_length=100, verbose_name='Area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('nom_Estudios', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ap', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('am', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto')),
                ('carrera', models.CharField(choices=[('sistemas', 'sistemas'), ('TICs', 'TICs'), ('Sofware', 'Sofware'), ('Ciencias de la computacion', 'Ciencias de la computacion'), ('Programador', 'Programador')], max_length=30, verbose_name='Carrera')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.area', verbose_name='Area')),
                ('estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.estudios', verbose_name='Estudios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
